Fix golang docker image registry path
Change from quay.io/lib/golang to quay.io/projectquay/golang
to match upstream and fix CI build failures.

Error was:
  Error: initializing source docker://quay.io/lib/golang:1.24:
  invalid status code from registry 405 (Method Not Allowed)

Signed-off-by: Swati Mulje <smulje@redhat.com>